config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  get '/', to: 'main#index'
  get 'index', to: 'main#index'

  get '/admin_login', to: 'admin_sessions#new'
  post '/admin_login', to: 'admin_sessions#create'
  delete '/admin_logout', to: 'admin_sessions#destroy'

  resources :users
  resources :works
  resources :work_cats
  resources :articles
  resources :article_cats
  resources :news
  resources :news_cats
  resources :cart_works
  post 'cart_works/delete', to: 'cart_works#delete'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'admin', to: 'main#admin'
  get 'admin_view', to: 'main#admin_view'
  post 'delete', to: 'main#delete'
  get 'concept', to: 'main#concept'
  get 'purchase', to: 'main#purchase'
  get 'thanks', to: 'main#thanks'
  get 'contact', to: 'main#contact'
  get 'help', to: 'main#help'
  get 'terms', to: 'main#terms'
  get 'policy', to: 'main#policy'

  get 'example', to: 'examples#index'
  get 'cost', to: 'examples#cost'
  get 'doraemon', to: 'examples#doraemon'
  post 'doraemon', to: 'examples#doraemon'


end

app/models/admin.rb
class Admin < ApplicationRecord
    has_secure_password
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :article_cat
    mount_uploader :image, ImageUploader
end

app/models/article_cat.rb
class ArticleCat < ApplicationRecord
    has_many :articles
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :cart_works, dependent: :destroy
    has_many :works, through: :cart_works
end

app/models/cart_work.rb
class CartWork < ApplicationRecord
    belongs_to :cart
    belongs_to :work
end

app/models/news.rb
class News < ApplicationRecord
    belongs_to :news_cat
    mount_uploader :image, ImageUploader
end

app/models/news_cat.rb
class NewsCat < ApplicationRecord
    has_many :news
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, #空白を許可しない
                        length: {minimum: 8}, #最低8文字必要とする
                        on: :create
    validates :email, presence: true,
                        length: { maximum: 255 },
                        uniqueness: true
    attr_accessor  :remember_token, :activation_token, :reset_token
    before_save   :downcase_email
    before_create :create_activation_digest
    
    has_one :cart
    # has_many :orders, dependent: :destroy

    mount_uploader :image, ImageUploader

    

    # ランダムな記憶トークンを返す
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    # 渡された文字列のハッシュ値を返す
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    # 上記２つのメソッドを利用し、生成された記憶トークンをハッシュ化
    # ハッシュ化した記憶トークンをDB（remember_digest）に保存する
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    # ユーザーのセッションをcookieに保存する（永続的セッション）
    def remember(user)
        user.remember
        cookies.permanent.encrypted[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
        # # cookiesに保存されたセッションに有効期限を設けたい場合（１ヶ月）
        # def remember(user)
        #     user.remember
        #     # cookies の有効期限を 1ヶ月 にしたい場合
        #     cookies.encrypted[:user_id] = { value: user.id, expires: 1.month.from_now }
        #     cookies[:remember_token] = { value: user.remember_token, expires: 1.month.from_now }
        # end
    # cookiesから渡されたトークンがダイジェスト(ハッシュ化されたトークン）と一致したらtrueを返す
    # 渡されたトークンがダイジェストと一致したらtrueを返す
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end
    # ユーザーの記憶ダイジェストを破棄する
    def forget
        update_attribute(:remember_digest, nil)
    end

    # 有効化用のメールを送信する
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
        update_attribute(:activation_sent_at, Time.zone.now)
    end
    # 有効化リンクの有効期限（24時間）が切れている場合はtrueを返す
    def activation_expired?
        activation_sent_at < 24.hours.ago
    end
    # アカウントを有効にする
    def activate
        update_attribute(:activated, true)
        update_attribute(:activated_at, Time.zone.now)
    end

    # パスワード再設定の属性を設定する
    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    # パスワード再設定のメールを送信する
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    # パスワード再設定の有効期限が切れている場合はtrueを返す
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    private
    # メールアドレスをすべて小文字にする
    def downcase_email
        self.email = email.downcase
    end
    # 有効化トークンとダイジェストを作成及び代入する
    def create_activation_digest
        self.activation_token = User.new_token
        self.activation_digest = User.digest(activation_token)
    end
end

app/models/work.rb
class Work < ApplicationRecord
    belongs_to :work_cat
    has_one :cart_work, dependent: :destroy
    has_one :cart, through: :cart_works
    mount_uploader :image, ImageUploader
end

app/models/work_cat.rb
class WorkCat < ApplicationRecord
    has_many :works
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cart_works_helper.rb
module CartWorksHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/news_cats_helper.rb
module NewsCatsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    # 現在ログイン中のユーザーを返す (いる場合)
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.encrypted[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def current_user?(user)
        user == current_user
    end

    def logged_in?
        !current_user.nil?
    end

    # 永続的セッションを破棄する
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    # ログアウトする（セッション情報を削除する）
    def log_out
        # ログアウト時に current_user の永続的セッションも破棄する
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_cats_helper.rb
module WorkCatsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CxxSew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <meta name="turbolinks-visit-control" content="reload"> %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_pack_tag 'common' %>
  </body>
</html>

app/views/layouts/example.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MANIACS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'examples', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <meta name="turbolinks-visit-control" content="reload"> %>
  </head>

  <body>
    <%= render 'examples/header' %>
    <%= yield %>
    <%= render 'examples/footer' %>
    <%= javascript_pack_tag 'common' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
	<a href="/" id="ft-center">
		<div>Cxx</div>
		<%= image_tag "/image/logo_negate.PNG", alt:"" %>
		<div>Sew</div>
	</a>
	<p>野村 宗佑　駒井 俊彦</p>
	<p>石川県金沢市利家城下町100万石</p>
	<p>cxxsew_million@gmail.com</p>
	<ul class="follow-links">
		<li class="follow-link"><a href="https://twitter.com" target="_blank"><%= image_tag "/svg/twiiter_w.svg", alt:"", class:"icon" %></a></li>
		<li class="follow-link"><a href="https://ja-jp.facebook.com" target="_blank"><%= image_tag "/svg/facebook_w.svg", alt:"", class:"icon" %></a></li>
		<li class="follow-link"><a href="https://www.instagram.com" target="_blank"><%= image_tag "/svg/instagram_w.svg", alt:"", class:"icon" %></a></li>
		<li class="follow-link"><a href="https://line.me" target="_blank"><%= image_tag "/svg/line_w.svg", alt:"", class:"icon" %></a></li>
	</ul>
	<small>(C) 2023 CxxSew.Inc All Rights Reserved.</small>
</footer>

app/views/shared/_header.html.erb
<header>
	<div id="hd-flex">
		<div class="hd-side pc">pc</div>
		<div class="toggle-btn sp">
			<div id="cross">
				<span class="menu-line-top"></span>
				<span class="menu-line-middle"></span>
				<span class="menu-line-bottom"></span>
			</div>
		</div>
		<a href="/" id="hd-center">
			<div>Cxx</div>
			<%= image_tag "/image/logo.PNG", alt:"" %>
			<div>Sew</div>
		</a>
		<% if admin_logged_in? %>
			<%= link_to "Log out", admin_logout_path, method: :delete, class:"hd-side" %>
		<% else %>
			<% if logged_in? %>
				<%= link_to "Log out", logout_path, method: :delete, class:"hd-side" %>
			<% else%>
				<a href="/login"><div class="hd-side">log in</div></a>
			<% end %>
		<% end %>
	</div>
</header>

<div class="hidden sp" id="sp-bg"></div>
<div class="hidden sp" id="sp-menu">
	<h1 class="menu-h2">- Menu -</h1>
	<div class="explain">
		<div class="rect-wrapper">
			<div class="rect-row">
				<a href="/concept"><p>CONCEPT</p></a>
				<a href="/news"><p>NEWS</p></a>
			</div>
			<div class="rect-row">
				<a href="/works"><p>WORKS</p></a>
				<a href="/articles"><p>CONTENTS</p></a>
			</div>
		</div>
	</div>
	<div class="explain">
		<div class="rect-wrapper" id="sub-menu2">
			<a href="/help">HELP</a>
			<a href="/contact">CONTACT</a>
			<a href="/policy">POLICY</a>
			<a href="/terms">TERMS</a>
		</div>
	</div>
</div>
	  

app/views/shared/view/_article.html.erb
<div class="table-name">
    <h1>投稿記事一覧</h1>
    <% if @articles.empty? %>
        <p>記事が投稿されていません。</p>
        <div class="btn"><a href="/articles/new">新規作成</a></div>
    <% else %>
        <div class="btn"><a href="/articles/new">新規作成</a></div>
        <p>記事数合計: <%= @articles.length %></p>
        <p>←データ列が多い場合は横スクロール→</p>
        <div class="table-wrapper" id="scroll-table">
            <div class="tr">
                <div class="th scroll-th check">
                    <input type="checkbox" id="check-all">
                </div>
                <div class="th scroll-th edit">EDIT</div>
                <div class="th scroll-th id">ID</div>
                <div class="th scroll-th image">IMAGE</div>
                <div class="th scroll-th name">TITLE</div>
                <div class="th scroll-th category">CATEGORY</div>
            </div>
            <% @articles.each do |article| %>
                <div class="tr">
                    <div class="td scroll-td check">
                        <input type="checkbox" class="delete-check">
                    </div>
                    <div class="td scroll-td edit">
                        <%= link_to '/articles/' + article.id.to_s + '/edit' do %>
                            <%= image_tag "/svg/edit.svg", class: 'icon', id: 'edit-icon' %>
                        <% end %>
                    </div>
                    <div class="td scroll-td id"><%= article.id %></div>
                    <div class="td scroll-td image">
                        <%= image_tag article.image.url, class: "table-image" %>
                    </div>
                    <div class="td scroll-td name"><%= article.title %></div>
                    <div class="td scroll-td category"><%= @article_cat_hash[article.article_cat_id] %></div>
                    
                </div>
            <% end %>  
        </div>
    <% end %>

    <%= form_with url: '/delete' do |form| %>
        <%= form.hidden_field "delete_list", {value: ''} %>
        <%= form.hidden_field "which", {value: 'article'} %>
        <%= form.submit "削除", class:"btn submit-btn", id:"delete-btn" %>
    <% end %>

    <div class="btn" id="submit-btn"><a href="/admin">管理画面トップへ</a></div>
</div>

app/views/shared/view/_article_cat.html.erb
<div class="table-name">
    <h1>記事カテゴリー 一覧</h1>
    <% if @article_cats.empty? %>
        <p>記事カテゴリーが投稿されていません。</p>
        <div class="btn"><a href="/article_cats/new">新規作成</a></div>
    <% else %>
        <div class="btn"><a href="/article_cats/new">新規作成</a></div>
        <p>記事カテゴリー数合計: <%= @article_cats.length %></p>
        <p>←データ列が多い場合は横スクロール→</p>
        <div class="table-wrapper" id="scroll-table">
            <div class="tr">
                <div class="th scroll-th check">
                    <input type="checkbox" id="check-all">
                </div>
                <div class="th scroll-th id">ID</div>
                <div class="th scroll-th name">NAME</div>
            </div>
            <% @article_cats.each do |article_cat| %>
                <div class="tr">
                    <div class="td scroll-td check">
                        <input type="checkbox" class="delete-check">
                    </div>
                    <div class="td scroll-td id"><%= article_cat.id %></div>
                    <div class="td scroll-td name"><%= article_cat.name %></div>
                </div>
            <% end %>  
        </div>
    <% end %>

    <%= form_with url: '/delete' do |form| %>
        <%= form.hidden_field "delete_list", {value: ''} %>
        <%= form.hidden_field "which", {value: 'article_cat'} %>
        <%= form.submit "削除", class:"btn submit-btn", id:"delete-btn" %>
    <% end %>
    
    <div class="btn" id="submit-btn"><a href="/admin">管理画面トップへ</a></div>
</div>

app/views/shared/view/_news.html.erb
<div class="table-name">
    <h1>ニュース一覧</h1>
    <% if @news.empty? %>
        <p>ニュースが投稿されていません。</p>
        <div class="btn"><a href="/news/new">新規作成</a></div>
    <% else %>
        <div class="btn"><a href="/news/new">新規作成</a></div>
        <p>ニュース数合計: <%= @news.length %></p>
        <p>←データ列が多い場合は横スクロール→</p>
        <div class="table-wrapper" id="scroll-table">
            <div class="tr">
                <div class="th scroll-th check">
                    <input type="checkbox" id="check-all">
                </div>
                <div class="th scroll-th edit">EDIT</div>
                <div class="th scroll-th id">ID</div>
                <div class="th scroll-th image">IMAGE</div>
                <div class="th scroll-th name">TITLE</div>
                <div class="th scroll-th category">CATEGORY</div>
            </div>
            <% @news.each do |news| %>
                <div class="tr">
                    <div class="td scroll-td check">
                        <input type="checkbox" class="delete-check">
                    </div>
                    <div class="td scroll-td edit">
                        <%= link_to '/news/' + news.id.to_s + '/edit' do %>
                            <%= image_tag "/svg/edit.svg", class: 'icon', id: 'edit-icon' %>
                        <% end %>
                    </div>
                    <div class="td scroll-td id"><%= news.id %></div>
                    <div class="td scroll-td image">
                        <%= image_tag news.image.url, class: "table-image" %>
                    </div>
                    <div class="td scroll-td name"><%= news.title %></div>
                    <div class="td scroll-td category"><%= @news_cat_hash[news.news_cat_id] %></div>
                    
                </div>
            <% end %>
        </div>
    <% end %>

    <%= form_with url: '/delete' do |form| %>
        <%= form.hidden_field "delete_list", {value: ''} %>
        <%= form.hidden_field "which", {value: 'news'} %>
        <%= form.submit "削除", class:"btn submit-btn", id:"delete-btn" %>
    <% end %>

    <div class="btn" id="submit-btn"><a href="/admin">管理画面トップへ</a></div>
</div>

app/views/shared/view/_news_cat.html.erb
<div class="table-name">
    <h1>ニュースカテゴリー 一覧</h1>
    <% if @news_cats.empty? %>
        <p>ニュースカテゴリーが投稿されていません。</p>
        <div class="btn"><a href="/news_cats/new">新規作成</a></div>
    <% else %>
        <div class="btn"><a href="/news_cats/new">新規作成</a></div>
        <p>ニュースカテゴリー数合計: <%= @news_cats.length %></p>
        <p>←データ列が多い場合は横スクロール→</p>
        <div class="table-wrapper" id="scroll-table">
            <div class="tr">
                <div class="th scroll-th check">
                    <input type="checkbox" id="check-all">
                </div>
                <div class="th scroll-th id">ID</div>
                <div class="th scroll-th name">NAME</div>
            </div>
            <% @news_cats.each do |news_cat| %>
                <div class="tr">
                    <div class="td scroll-td check">
                        <input type="checkbox" class="delete-check">
                    </div>
                    <div class="td scroll-td id"><%= news_cat.id %></div>
                    <div class="td scroll-td name"><%= news_cat.name %></div>
                </div>
            <% end %>  
        </div>
    <% end %>

    <%= form_with url: '/delete' do |form| %>
        <%= form.hidden_field "delete_list", {value: ''} %>
        <%= form.hidden_field "which", {value: 'news_cat'} %>
        <%= form.submit "削除", class:"btn submit-btn", id:"delete-btn" %>
    <% end %>
    
    <div class="btn" id="submit-btn"><a href="/admin">管理画面トップへ</a></div>
</div>

app/views/shared/view/_user.html.erb
<div class="table-name">
    <h1>登録者一覧</h1>
    <% if @users.empty? %>
        <p>登録者が存在していません。</p>
    <% else %>
    <p>登録者合計: <%= @users.length %></p>
    <div class="table-wrapper">
        <table>
            <div class="tr">
                <div class="th">ID</div>
                <div class="th">IMAGE</div>
                <div class="th">NAME</div>
            </div>
            <% @users.each do |user| %>
                <div class="tr">
                    <div class="td"><%= user.id %></div>
                    <div class="td">
                        <%= image_tag user.image.to_s, class: "table-image" %>
                    </div>
                    <div class="td"><%= user.name %></div>
                </div>
            <% end %>
        </table>
    </div>
    <% end %>
    <div class="btn" id="submit-btn"><a href="/admin">管理画面トップへ</a></div>
</div>

app/views/shared/view/_work.html.erb
<div class="table-name">
    <h1>商品一覧</h1>
    <% if @works.empty? %>
        <p>商品が投稿されていません。</p>
        <div class="btn"><a href="/works/new">新規作成</a></div>
    <% else %>
        <div class="btn"><a href="/works/new">新規作成</a></div>
        <p>商品数合計: <%= @works.length %></p>
        <p>←データ列が多い場合は横スクロール→</p>
        <div class="table-wrapper" id="scroll-table">
            <div class="tr">
                <div class="th scroll-th check">
                    <input type="checkbox" id="check-all">
                </div>
                <div class="th scroll-th edit">EDIT</div>
                <div class="th scroll-th id">ID</div>
                <div class="th scroll-th image">IMAGE</div>
                <div class="th scroll-th name">NAME</div>
                <div class="th scroll-th category">CATEGORY</div>
            </div>
            <% @works.each do |work| %>
                <div class="tr">
                    <div class="td scroll-td check">
                        <input type="checkbox" class="delete-check">
                    </div>
                    <div class="td scroll-td edit">
                        <%= link_to '/works/' + work.id.to_s + '/edit' do %>
                            <%= image_tag "/svg/edit.svg", class: 'icon', id: 'edit-icon' %>
                        <% end %>
                    </div>
                    <div class="td scroll-td id"><%= work.id %></div>
                    <div class="td scroll-td image">
                        <%= image_tag work.image.url, class: "table-image" %>
                    </div>
                    <div class="td scroll-td name"><%= work.title %></div>
                    <div class="td scroll-td category"><%= @work_cat_hash[work.work_cat_id] %></div>
                    
                </div>
            <% end %>   
        </div>
    <% end %>

    <%= form_with url: '/delete' do |form| %>
        <%= form.hidden_field "delete_list", {value: ''} %>
        <%= form.hidden_field "which", {value: 'work'} %>
        <%= form.submit "削除", class:"btn submit-btn", id:"delete-btn" %>
    <% end %>
    
    <div class="btn" id="submit-btn"><a href="/admin">管理画面トップへ</a></div>
</div>

app/views/shared/view/_work_cat.html.erb
<div class="table-name">
    <h1>商品カテゴリー 一覧</h1>
    <% if @work_cats.empty? %>
        <p>商品カテゴリーが投稿されていません。</p>
        <div class="btn"><a href="/work_cats/new">新規作成</a></div>
    <% else %>
        <div class="btn"><a href="/work_cats/new">新規作成</a></div>
        <p>商品カテゴリー数合計: <%= @work_cats.length %></p>
        <p>←データ列が多い場合は横スクロール→</p>
        <div class="table-wrapper" id="scroll-table">
            <div class="tr">
                <div class="th scroll-th check">
                    <input type="checkbox" id="check-all">
                </div>
                <div class="th scroll-th id">ID</div>
                <div class="th scroll-th name">NAME</div>
            </div>
            <% @work_cats.each do |work_cat| %>
                <div class="tr">
                    <div class="td scroll-td check">
                        <input type="checkbox" class="delete-check">
                    </div>
                    <div class="td scroll-td id"><%= work_cat.id %></div>
                    <div class="td scroll-td name"><%= work_cat.name %></div>
                </div>
            <% end %>  
        </div>
    <% end %>

    <%= form_with url: '/delete' do |form| %>
        <%= form.hidden_field "delete_list", {value: ''} %>
        <%= form.hidden_field "which", {value: 'work_cat'} %>
        <%= form.submit "削除", class:"btn submit-btn", id:"delete-btn" %>
    <% end %>
    
    <div class="btn" id="submit-btn"><a href="/admin">管理画面トップへ</a></div>
</div>